paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      description: Retorna una lista de todos los productos disponibles en la tienda.
      tags: 
        - product
      responses:
        '200':
          description: Lista de productos exitosamente obtenida.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /api/products/new:
    get:
      summary: Mostrar formulario para agregar un nuevo producto
      description: Muestra un formulario para agregar un nuevo producto.
      tags: 
        - product

  /api/products/{pid}:
    get:
      summary: Obtener un producto por ID
      description: Retorna un producto específico por su ID.
      tags: 
        - product
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a buscar.
          schema:
            $type: String
      responses:
        '200':
          description: Producto exitosamente encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado.
    put:
      summary: Actualizar un producto por ID
      description: Actualiza un producto específico por su ID.
      tags: 
        - product
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a actualizar.
          schema:
            type: integer
      requestBody:
        description: Datos del producto actualizado.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado.

    delete:
      summary: Eliminar un producto por ID
      description: Elimina un producto específico por su ID.
      tags: 
        - product
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a eliminar.
          schema:
            type: integer
      responses:
        '204':
          description: Producto eliminado exitosamente.
        '404':
          description: Producto no encontrado.

components:
  schemas:
    Product:
      type: object
      properties:
        _id: 
          type: ObjectId
          description: ID auto generado por mongo
        title:
          type: string
          description: Titulo del producto
        code:
          type: number  
          description: Codigo autogenerado
        price:
          type: number
          description: Precio del producto
        stock:
          type: number    
          description: Cantidad de stock disponible del producto
        category:
          type: string
          description: Categoria a la que pertenece el producto
        thumbnail:
          type: string
          description: Imagen del producto
        owner:
          type: string
          description: Usuario que creo el producto (email)     
      example:
        _id: ObjectId("652acba407d8295adeab421d")
        title: Silla Gamer
        description: Silla gamer con rueditas
        code: 01
        price: 100
        stock: 5
        category: Accesorios
        thumbnail: imagen
        owner: example@gmail.com